### PR TITLE
modify: rotate only for the current picture instead of all the pictures

### PR DESCRIPTION
**Pull request by wujingacross**
Changed all the pictures are rotating problem, but there will be some rotation effect.

### CODE REVIEW

**Comment by Horat1us** [comment]
This will reset angle for previous image.
For example, we have 2 images.
1. User rotates first image (angle=90)
2. User switches to image 2 (angle=0)
3. User switches back to first image and previous rotation wasn't stored (angle=0)

It's important for me to store rotation after changing image. If you can change your PR, I will merge it.

**Comment by Horat1us** [comment]
Main point is to restore rotation angle for previous image.

**Comment by wujingacross** [comment]
You mean saving only the rotation angle of a picture？
For example, we have 3 images.
1. User rotates first image (angle=90)
2. User switches to image 2 (angle=0) 
    Here to remember the first rotation angle.
3. User switches to image 3
    Here need to remember the second picture of the rotation angle ？
Only retain the previous picture angle ?

Since the magnification of the original component react-image-lightbox has not been saved yet, is it better to deal with it uniformly?

**Comment by wujingacross** [comment]
There are only remember the previous picture, If the latter has a rotation, do not need to remember the last one?
For example, we have 2 images.

1. User rotates first image (angle=0)
2. User switches to image 2 (angle=90)
3. Switch to image 1 and switch back to image 2

Is the current image 2 need to have a rotation angle?

**Comment by Horat1us** [comment]
Yes, in your second example: image 2 need to have a rotation angle.

**Comment by wujingacross** [comment]
The first question is whether you want to save the angle of a picture before or after, or whether you want all the pictures to be preserved？

**Comment by Horat1us** [comment]
I want all pictures to be preserved, but I'm not sure it's real with `react-image-lightbox`.
In case it is not real saving pictures before and after will be ok.

**Comment by wujingacross** [comment]
Recently more busy, temporary preservation of the picture before and after the rotation angle is controlled by the parameters

**Review by Horat1us — APPROVED** [review]

**Comment by Horat1us** [comment]
Thanks for your contribution! You can use version `v1.2.0`

**Pull request merged**
